config/routes.rb
Tenkuai::Application.routes.draw do
  get "fake_paypal/index"

  resources :sent, :messages, :mailbox, :roles, :categories, :orders

  match "inbox" => "mailbox#index"

  devise_for :users, :path_names => { :sign_up => "join", :sign_in => "login"}, :controllers =>{:registrations => 'users/registrations'}

  resources :users, :only=>[:show] do
    resources :shirs 
    resources :sent
    resources :mailbox do
      resources :sent
    end
  end
  resources :shirs do 
    resources :orders
  end

  get "/:user_id/:id", :to => "shirs#show", :as => :shirs_user
  get "/:user_id/message/:id/sent/new", :to => "sent#new", :as => :user_mailbox_sent

  get "home/index"
  get "fake_paypal/i/:shir_id", :to => "fake_paypal#index", :as => :fake_paypal_shir

  root :to => 'home#index'

  match ':id' => "users#show", :as => :username

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :role_ids, :debug, 
                  :introduction, :website, :country, :city, :photo_file_name, :photo_content_type, 
                  :photo_file_size, :photo, :cached_slug
  
  #add the friendly id as username
  extend FriendlyId
  friendly_id :username, :use => :slugged
  
  #sql relation between tables
  has_many :shirs
  has_and_belongs_to_many :roles
  has_many :orders
  has_many :sent_messages, :class_name => "Message", :foreign_key => "author_id"
  has_many :received_messages, :class_name => "MessageCopy", :foreign_key => "recipient_id"
  has_many :folders
  
  before_create :setup_role, :build_inbox
  
  def inbox
  folders.find_by_name("Inbox")
  end
  
  def build_inbox
    folders.build(:name =>"Inbox")
  end

  #allow to save the edit form without typing password
  def update_with_password(params={})
    params.delete(:current_password)
    self.update_without_password(params)
  end
  
  #conf for the profile pictures
  has_attached_file :photo,
      :styles => {
        :thumb=> "100x100!",
        :small  => "150x150!" }

  #setup default role
  def setup_role 
       if self.role_ids.empty?     
         self.role_ids = [3] 
       end
     end

    #featured
    
    scope :featured, :conditions => {:featured => true}

  #check the username field
  validates :username, :presence=>true,:uniqueness=>true, :format => {:with => /^[A-Za-z0-9_\.@]+$/}, :length => {:minimum => 3, :maximum => 20}
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_update_path_for(resource)
    username_path(resource)
  end

  def after_sign_up_path_for(resource)
    username_path(resource)
  end
  
   def after_sign_in_path_for(resource)
     username_path(resource)
   end
   
   
 
def edit
  super
end
def new
  super
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  before_filter :authenticate_user!, :except => [:show]


  # GET /users/1
  # GET /users/1.json
  def show
    
    @user = User.find(params[:id])
    @shirs = @user.shirs ? @user.shirs.order('created_at DESC') : {}
    @user_created_at = Time.at(@user.created_at.to_i)
    @introduction = @user.introduction ? @user.introduction : ''
    @website = @user.website ? @user.website : ''
    @photo = @user.photo_file_name ? @user.photo.url(:small) : 'test/santa.jpg'
    @username = @user.username
    @bought = Order.where(:user_id => @user.id)
    @sold = Order.where(:shir_id => @shirs)
    @title = @username
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @user }
      end
    end

    # GET /users/new
    # GET /users/new.json
    # def new
    #          @user = User.new
    #       
    #           respond_to do |format|
    #             format.html # new.html.erb
    #             format.json { render :json => @user }
    #           end
    #         end

    # GET /users/1/edit
    # def edit
    #                  redirect_to "/users/edit"
    #                  @user = User.find(params[:id])
    #                end

    # POST /users
    # POST /users.json
    # def create
    #                 
    #                         @user = User.new(params[:user])
    #                     
    #                         respond_to do |format|
    #                           if @user.save
    #                             format.html { redirect_to @user, :notice => 'User was successfully created.' }
    #                             format.json { render :json => @user, :status => :created, :location => @user }
    #                           else
    #                             format.html { render :action => "new" }
    #                             format.json { render :json => @user.errors, :status => :unprocessable_entity }
    #                           end
    #                         end
    #                       end
    #             
    # PUT /users/1
    # PUT /users/1.json
    # def update
    #       @user = User.find(params[:id])
    #   
    #       respond_to do |format|
    #         if @user.update_attributes(params[:user])
    #           format.html { redirect_to @user, :notice => 'User was successfully updated.' }
    #           format.json { head :ok }
    #         else
    #           format.html { render :action => "edit" }
    #           format.json { render :json => @user.errors, :status => :unprocessable_entity }
    #         end
    #       end
    #     end

    # DELETE /users/1
    # DELETE /users/1.json
    # def destroy
    #        @user = User.find(params[:id])
    #        @user.destroy
    #    
    #        respond_to do |format|
    #          format.html { redirect_to users_url }
    #          format.json { head :ok }
    #        end
    #      end
  end

app/helpers/users_helper.rb
module UsersHelper
  def format_shir
    shirs = @user.shirs.count
    return 'Shirs ('<<shirs.to_s<<')' if shirs > 1
   'Shir'
  end
end

app/views/users/_left.html.erb
<%= image_tag @photo, :alt =>"#{@username}'s profile picture", :id => "profilePic"%>
<h1 class="capitalize left"><%= @username %></h1>

<br class="clear">

<div class="profileDetails">
	<ul>
		<li>
			<div class="left">User</div> <!-- left --> 
			<div class="capitalize" class="right"><%= @user.username %></div> <!-- right -->
			<div class="clear"></div>
		</li>

		<li>
			<div class="left">Location</div> <!-- left --> 
			<div class="right">
				<%=city @user.city, @user.country%>
				<%=country @user.country%>
			</div> <!-- right -->
			<div class="clear"></div>
		</li>

		<li>
			<div class="left">Website</div> <!-- left --> 
			<div class="right"><a href="http://<%=@website%>" target="_blank"><%=@website%></a></div> <!-- right -->
			<div class="clear"></div>
		</li>

		<li>
			<div class="left">Member Since</div> <!-- left --> 
			<div class="right">
				<%=@user_created_at.strftime('%d %b %Y')%>
			</div> <!-- right -->
			<div class="clear"></div>
		</li>

	</ul>
	<p class="c888">Introduction</p>
	<p><%=@introduction%></p>
bought: <%@bought.each do |b|%><%=link_to b.shir.title, shirs_user_path(b.shir.user.username, b.shir)%>,<%end%><br />
sold: <%@sold.each do |s|%><%=s.shir.title%><%end%>
</div>

app/views/users/_middle.html.erb
<%if user_signed_in?%>
<%if own_by? @user%>
<% if can? :create, Shir%>
<div class="orderMain">
	<%= link_to 'Add New Shir', new_shir_path%>
</div> <!-- orderMain -->
<%end%>
<div id="colMiddleUl">
	<%=link_to 'View Messages', inbox_path %>
	<%=link_to 'Edit Account Settings', edit_user_registration_path %>
	<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
</div>
<%else%>
<div class="orderMain">
	<%= link_to 'Message User', new_user_sent_path(@user) %>
</div> <!-- orderMain -->
<%end%>
<%else%>
<div class="orderMain">
	<%= link_to 'Message User', new_user_registration_path %>
</div> 
<%end%>

<div class="clear"><br></div>

app/views/users/_right.html.erb
<div class="userWrap">
	<h2><%= @user.username %>'s
		<%=format_shir%>

		<div class="activityEntry">
			<ul>

				<% @shirs.each do |s| %>
				<li>
					<%unless s.photo_file_name.nil?%>
					<%= image_tag s.photo.url(:thumb), :alt =>"#{s.title}", :id => "profilePic"%>
					<%else%>
					<%= image_tag("test/latestImg1.jpg", :alt => "Post Photo") %>
					<%end%>
					<div class="activityEntryDesc">
						<p class="small"><%= s.created_at.strftime('%d %b %Y')%></p>
						<h4><%=link_to s.title, shirs_user_path(@user, s) %></h4>
					</div> <!-- activityEntryDesc -->
					<div class="clear"></div>
				</li>
				<% end %>
			</ul>
		</div> <!-- activityEntry -->
		<%unless @shirs.count < 4%>
		<p class="center">
			<span class="up">
				<%= image_tag("up.png", :alt => "Up") %>
			</span> 
			<span class="down">
				<%= image_tag("down.png", :alt => "Down") %>
			</span>
		</p>
		<%end%>

	</div> <!-- userWrap -->

app/views/users/show.html.erb
<%title "#{@user.username.capitalize}"%>
<div id="user" class="wrap">
	<div class="colLeft">
		<%=render 'left'%>
		<!-- profileDetails -->
	</div> <!-- colLeft -->

	<div class="colMiddle"> 
		<%=render 'middle'%>
	</div> <!-- colMiddle -->

	<div class="colRight">
		<%=render 'right'%>
	</div> <!-- colRight -->

	<div class="clear"></div>
</div> <!-- wrap -->