config/routes.rb
Tenkuai::Application.routes.draw do
  get "fake_paypal/index"

  resources :sent, :messages, :mailbox, :roles, :categories, :orders

  match "inbox" => "mailbox#index"

  devise_for :users, :path_names => { :sign_up => "join", :sign_in => "login"}, :controllers =>{:registrations => 'users/registrations'}

  resources :users, :only=>[:show] do
    resources :shirs 
    resources :sent
    resources :mailbox do
      resources :sent
    end
  end
  resources :shirs do 
    resources :orders
  end

  get "/:user_id/:id", :to => "shirs#show", :as => :shirs_user
  get "/:user_id/message/:id/sent/new", :to => "sent#new", :as => :user_mailbox_sent

  get "home/index"
  get "fake_paypal/i/:shir_id", :to => "fake_paypal#index", :as => :fake_paypal_shir

  root :to => 'home#index'

  match ':id' => "users#show", :as => :username

end

app/models/shir.rb
class Shir < ActiveRecord::Base
  #sql relation between tables
  belongs_to :user
  belongs_to :category
  has_many :orders
  belongs_to :organisation
  
  scope :featured, :conditions => {:featured => true}
  scope :recent, where('created_at>= ?', Time.now-1.week)
  #tag to shirs
  acts_as_taggable

  #use friendly id as title
  extend FriendlyId
  friendly_id :title, :use => :slugged

  #check validity of fields
  validates :title, :presence=>true, :length => {:minimum =>10, :maximum => 100}
  validates :category, :presence => true
  validates :description, :presence => true, :length => {:minimum => 40, :maximum => 555}
  validates :instruction, :presence => true, :length => {:minimum => 40, :maximum => 555}
  validates :tag_list, :presence => true
  validates :photo_file_name, :presence => true

  #conf for the profile pictures
  has_attached_file :photo,
  :styles => {
    :thumb=> "97x97!",
    :small  => "306x132!",
    :medium => "310x220!" }
  end

app/controllers/shirs_controller.rb
class ShirsController < ApplicationController
  # GET /shirs
  # GET /shirs.json

  before_filter :get_categories


  def index
    @shirs = Shir.count > 0 ? Shir.order('created_at desc') : {}
    @recent_shir = Shir.recent
    if params[:tags]
      @shirs = Shir.tagged_with(params[:tags])
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @shirs }
    end
  end

  # GET /shirs/1
  # GET /shirs/1.json
  def show
   
    @shir = Shir.find(params[:id])
    @user = @shir.user
    @photo = @shir.photo_file_name ? @shir.photo.url(:medium) : 'test/shirMainImg.jpg'
    @category = @shir.category ? @shir.category : ''
     @title = "#{@shir.title} by #{@shir.user.username}"
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @shir }
    end

  end

  # GET /shirs/new
  # GET /shirs/new.json
  def new
    @shir = Shir.new
    authorize! :create, @shir
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @shir }
    end
  end

  # GET /shirs/1/edit
  def edit
    @categories = Category.all
    @shir = Shir.find(params[:id])
    @user = current_user
    authorize! :edit, @shir
  end

  # POST /shirs
  # POST /shirs.json
  def create
    @shir = Shir.new(params[:shir])
    @shir.user_id = current_user.id
    respond_to do |format|
      if @shir.save
        format.html { redirect_to @shir, :notice => 'Shir was successfully created.' }
        format.json { render :json => @shir, :status => :created, :location => @shir }
      else
        format.html { render :action => "new" }
        format.json { render :json => @shir.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shirs/1
  # PUT /shirs/1.json
  def update
    @shir = Shir.find(params[:id])
    @shir.user_id = current_user.id
    respond_to do |format|
      if @shir.update_attributes(params[:shir])
        format.html { redirect_to @shir, :notice => 'Shir was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @shir.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shirs/1
  # DELETE /shirs/1.json
  def destroy
    @shir = Shir.find(params[:id])
    @shir.destroy

    respond_to do |format|
      format.html { redirect_to username_url(@shir.user.username.downcase) }
      format.json { head :ok }
    end
  end
end

app/helpers/shirs_helper.rb
module ShirsHelper
end

app/views/shirs/show/_left.html.erb
	<h1><%= @shir.title.capitalize %></h1>
		<%= image_tag @photo, :alt => @shir.title, :class=> "mainImg" %>
		<p><%= @shir.description.capitalize %></p>
		
		<h3>Instructions</h3>
		
		<p><%= @shir.instruction.capitalize %></p>
		
		

app/views/shirs/show/_middle.html.erb
<%if not_own_by? @user%>

<!-- <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
	<input type="hidden" name="cmd" value="_s-xclick">
	<input type="hidden" name="hosted_button_id" value="VXKP7SGYHFXQ2">
	<input type="hidden" name="item_name" value="<%= @shir.title.capitalize %> by <%= @user.username%> for <%=current_user.username%>"> 
	<input type="submit" class="orderMain buyPaypal" value="Buy This" name="submit">
</form>         -->
<%=link_to "Buy This", fake_paypal_shir_path(@shir.id), :class => "orderMain buyPaypal"%>
<!-- link_to "buy this", new_shir_order_path(@shir) -->

<%=link_to "Ask the seller a question", root_path, :id => "askQuestion"%>
<%elsif !user_signed_in?%>
<div class="orderMain">

	<%=link_to "buy this", new_user_registration_path %>

</div> <!-- orderMain -->

<%=link_to "Ask the seller a question!", new_user_registration_path, :id => "askQuestion"%>

<%end%>
<div id="feedback">
	<h4>Latest Buyer Feedback</h4>

	<div class="feedbackList">
		<ul>
			<li>
				<%= image_tag("test/feedbackImg.jpg", :alt => "username", :class=> "left") %>
				<div class="right"><a href="">Gengis Khan</a> <div class="smaller">posted this 1 day ago</div></div>
				<div class="clear"></div>
				<p>excellent work on time, i recommend to everyone try, must encourage arjunrocks to climb greater heights</p>
			</li>

			<li>
				<%= image_tag("test/feedbackImg.jpg", :alt => "username", :class=> "left") %>
				<div class="right"><a href="">Mark Zuckerberg</a> <div class="smaller">posted this 1 day ago</div></div>
				<div class="clear"></div>
				<p>You did an amazing job! Thanks so much for your time, Ill let you know how my coworker reacts :)</p>
			</li>

			<li>
				<%= image_tag("test/feedbackImg.jpg", :alt => "username", :class=> "left") %>
				<div class="right"><a href="">Sean Kingston</a> <div class="smaller">posted this 1 day ago</div></div>
				<div class="clear"></div>
				<p>Fantastic!!!!! It was very good! I see why you are a top-seller!</p>
			</li>
		</ul>
	</div> <!-- feedbackList -->
	<p class="center"><span class="up"><%= image_tag("up.png", :alt => "Up") %></span> <span class="down"><%= image_tag("down.png", :alt => "Down") %></span></p>
</div> <!-- feedback -->

app/views/shirs/show/_right.html.erb
<div id="share">
			<span class='st_sina_button' displayText='Sina'></span><span class='st_twitter_button' displayText='Tweet'></span><span class='st_email_button' displayText='Email'></span><span  class='st_facebook_button' displayText='Facebook'></span>
		</div> <!-- share -->

		<div class="shirWrap">

			<div id="productMisc">

				<div class="pRowThick">
					<h4>About this Shi'r</h4>
					<%if can? :edit, @shir%>
					<%= link_to 'Edit Shir', edit_shir_path(@shir), :class=>"small", :id=>"editShir" %>
					<%end%>
					<span class="clear"></span>
				</div>

				<div class="pRow">
					<div class="c444 left">Shi'r Rating</div>
					<div class="right"> 

					</div>
					<div class="clear"></div>
				</div>

				<div class="pRow">
					<div class="c444 left">Delivery Time</div>
					<div class="right">
						<%=pluralize(@shir.days_to_complete, "day")%>
					</div>
					<div class="clear"></div>
				</div>

				<div class="pRow">
					<div class="c444 left">Orders in Queue</div>
					<div class="right">0</div>
					<div class="clear"></div>
				</div>

				<div class="pRowThick bold">
					<div class="left">Seller : </div>
					<div class="right"></div>
					<div class="clear"></div>
				</div>

				<div class="pRow">
					<div class="left">
						<%= link_to @user.username, username_path(@user.username.downcase) %>
					</div>
					<div class="right">
						<%=city @user.city, @user.country%>
						<%=country @user.country%>

					</div>
					<div class="clear"></div>
				</div>

				<div class="pRow">
					<div class="c444 left">Created this Shir</div>
					<div class="right"><%=time_ago_in_words(@shir.created_at.to_time)%> ago</div>
					<div class="clear"></div>
				</div>

				<div class="pRowThick bold">
					<div class="left">Category : </div>

					<div class="right"></div>
					<div class="clear"></div>
				</div>


				<div class="pRow">
					<div class="left">
						<%if @category != ''%>
						<%= link_to @category.title, category_path(@category) %>
						<%end%>
					</div>
					<div class="right">-</div>
					<div class="clear"></div>
				</div>

				<div class="pRowThick bold">
					<div class="left">Tagged as : </div>
					<div class="right"></div>
					<div class="clear"></div>
				</div>

				<div id="taggedAs">
					<% @shir.tags.each do |t|%>
					<%=link_to t.name, "#{shirs_path}?tags=#{t.name}"%>
					<%end%>
					<span class="clear"></span>
				</div>

				<div class="clear"></div>

			</div> <!-- shirWrap -->
		</div> <!-- productMisc -->