config/routes.rb
Tenkuai::Application.routes.draw do
  get "fake_paypal/index"

  resources :sent, :messages, :mailbox, :roles, :categories, :orders

  match "inbox" => "mailbox#index"

  devise_for :users, :path_names => { :sign_up => "join", :sign_in => "login"}, :controllers =>{:registrations => 'users/registrations'}

  resources :users, :only=>[:show] do
    resources :shirs 
    resources :sent
    resources :mailbox do
      resources :sent
    end
  end
  resources :shirs do 
    resources :orders
  end

  get "/:user_id/:id", :to => "shirs#show", :as => :shirs_user
  get "/:user_id/message/:id/sent/new", :to => "sent#new", :as => :user_mailbox_sent

  get "home/index"
  get "fake_paypal/i/:shir_id", :to => "fake_paypal#index", :as => :fake_paypal_shir

  root :to => 'home#index'

  match ':id' => "users#show", :as => :username

end

app/models/category.rb
class Category < ActiveRecord::Base
  #link with Shir
  has_many :shirs
  
  #use title for path
  extend FriendlyId
  friendly_id :title, :use => :slugged
  
  validates :title, :presence => true, :length =>{:minmum => 2, :maximum => 20}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_filter :get_categories
  
  def get_categories
  @categories = Category.all
  end
  
  # GET /categories
  # GET /categories.json
  def index

    @categories = Category.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    authorize! :create, @category

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    authorize! :edit, @category
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    authorize! :create, @category
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, :notice => 'Category was successfully created.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])
    authorize! :update, @category
    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, :notice => 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    authorize! :destroy, @category
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :shir_id %><br />
    <%= f.number_field :shir_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

 <%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%if can? :read, @category%>
<h1>Listing categories</h1>
<table>
	<tr>
		<th>Title</th>
		<th>Desc</th>
    <th>Shir</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% @categories.each do |category| %>
	<tr>
		<td><%= category.title %></td>
		<td><%= category.desc %></td>
		<!-- <%if category.shirs.count != 0%>
		<%category.shirs.each do |c| %>
		<td></td>
		<%end%>
		<%else%> -->
		<td>no category</td>
		<!-- <%end%> -->
		<td><%= link_to 'Show', category %></td>
		<%if can? :edit, @category%>
		<td><%= link_to 'Edit', edit_category_path(category) %></td>
		<%end%>
		<%if can? :destroy, @category%>
		<td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
		<%end%>
	</tr>
	<% end %>
</table>

<br />
<%if can? :create, @categories%>
<%= link_to 'New Category', new_category_path %>
<%end%>
<%end%>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div id="listings" class="wrap">

	<div class="colLeft">
	<h2>Featured in : <span class="ctit c111"><%= @category.title %></span></h2>
	</div> <!-- colLeft -->

	<div class="colMiddle">
    
    <div id="colMiddleUl">
		  <% Category.all.each do |c| %>
		  <%= link_to c.title, c %>
			<% end %>
		</div> <!-- categories -->
		
	</div> <!-- colMiddle -->

	<div class="colRight">
	
	<h2>Newest in : <span class="ctit c111"><%= @category.title %></span></h2>
	
	<div class="shirEntry">
	  <ul>
		
	  <%unless @category.shirs.nil?%>
    <%@category.shirs.each do |c|%>
  
      <li>
  			<%= image_tag c.photo(:thumb), :alt =>"#{c.title}", :id => "profilePic" %>
  			<div class="shirEntryDesc">
  			<p class="small">For 20 kuai, <%=link_to c.user.username, "/#{c.user.username.downcase}", :class =>"capitalize" %> will..</p>
  			<h4><%=link_to c.title, user_shir_path(c.user, c)%></h4>
  			</div> <!-- shirEntryDesc -->
  			<div class="clear"></div>
  		</li>
		
    <%end%>
    <%end%>
    
    </ul>
  </div> <!-- shirEntry -->
  
	</div> <!-- colRight -->

	<div class="clear"></div>
	
</div> <!-- wrap -->